### ISSUE TITLE
The `linux-fs-simple` example fails to build

### ISSUE THREAD

**Issue by jgalar** [efficios/barectf#27]
Running `c4c4606`, the `linux-fs-simple` example fails to build with the following error:

```
❯ make
barectf config.yaml -m trace
Configuration: Cannot create configuration from YAML file
Configuration object:
`trace` property:
`type` property:
`data-stream-types` property:
`default` property:
`event-record-types` property:
`bit_packed_integers` property:
`payload-field-type` property:
`members` property:
Element #6:
`int5` property:
`field-type` property: Additional properties are not allowed ('byte-order' was unexpected) (from schema `config/3/config`)
make: *** [Makefile:45: barectf.h] Error 1
```

**Comment by ebugden** [comment]
I don't believe this error could have happened without modifying the example's [configuration file](https://github.com/efficios/barectf/blob/master/examples/linux-fs-simple/config.yaml#L27). `linux-fs-simple` uses a barectf 3 configuration file, so if the configuration was changed to use `byte-order` which is a barectf 2 property it would fail since, in barectf 3, `byte-order` is an invalid config property. **My guess is that it would build if the v3 property, `native-byte-order`, was used instead.**

----

Some possible underlying design issues are:
* **The project examples are not clearly identified as barectf 2 or barectf 3?** I believe `barectf-tracepoint` uses a v2 config file and `linux-fs-simple` uses v3, but I don't remember seeing anything in their readmes indicating this explicitly. You would need to be familiar with the differences in configuration file to figure this out. 
  * Alternatively, **should we consider replacing the v2 example with a v3 example?** My understanding is that we would prefer to not have new v2 users. Additionally it's (rightfully) tricky to get your hands on barectf 2 doc. I think the last vestiges are the [github project wiki](https://github.com/efficios/barectf/wiki/Writing-the-YAML-configuration-file).
* **In general, maybe it is not sufficiently obvious when you're using a barectf 3 or barectf 2 file?** Because v2 and v3 config files are identified with different structures it's less immediately obvious (see just below). I expect this would primarily be a problem for new users of barectf or users transitioning from v2 to v3.
  * barectf 2: Version identified in the configuration object `version: '2.2'`
  * barectf 3: Version identified by a YAML tag `--- !<tag:barectf.org,2020/3/config>`
* **The error messages used when a valid barectf 2 property in barectf 3 should give more hints to the user?** It could be confusing and frustrating to use a property that was previously valid in the context of barectf 2. The reflex could be to assume that barectf 3 is broken (as was the case in this issue report).

There are probably some small adjustments we could make that would some of these things more obvious. @eepp what do you think?

**Comment by jgalar** [comment]
To confirm what @ebugden told me in person, I had local modifications to the configuration file: sorry about the noise and thanks! 😬

Ultimately my configuration was indeed malformed so it's on me.

Still, I'll pitch-in on some of your points as a quidam using barectf.

### Regarding configuration versions

I personally like file extensions to indicate what a file's contents are expected to be (i.e. perhaps `.bctf2`, `.bctf3` instead of the generic `.yaml`).

For example, the session configurations of LTTng-tools are XML files with a `.lttng` extension as a hint that those aren't "generic" XML files. However, it leads to other usability challenges as graphical shells and naive text editors will fail to identify the files as being XML documents.

It's not cut and dry though; I respect that it comes down to the software author's preference.

### Regarding error messages

I think it can be a good idea to have an error message specific to old property names that no longer exist as a helper. I'm not thinking of anything fancy here; just a plain old `list` that unknown properties are compared against to produce a message like:

```
Unrecognized property `blah-bleh`: this property no longer exists in barectf v3.
```

It doesn't provide a solution, but at least it can spark a "**hmm!**" moment.

**Comment by ebugden** [comment]
Thank you for this feedback! :sunflower: 

(@eepp I think this particular issue could be closed. A new one could be opened if we decide to look into some design bumps.)
